### ISSUE TITLE
Hello world module compiling but not working!

### ISSUE THREAD

**Issue by snayaksnayak** [norayr/voc#21]
I compiled and installed Vishop Oberon compiler 1.1 on my linux.
Below is my Hello.Mod file collected from net.
I compiled the file using voc -m. It went fine.
When I tried to run the module using ./Hello, I see nothing. :-(
What is that I missed? Why it is not working?

~# cat Hello.Mod
MODULE Hello;
         IMPORT Oberon, Texts;
  VAR W: Texts.Writer;
    PROCEDURE World*;
  BEGIN
    Texts.WriteString(W, "Hello World!");
    Texts.WriteLn(W);
    Texts.Append(Oberon.Log, W.buf);
  END World;

BEGIN
  Texts.OpenWriter(W);
END Hello.

**Comment by norayr** [comment]
Hey hey, Srinivas!

I am glad you are trying to use voc!

First remark - it's better to use git version, not the release. Git versian has many improvements and fixes.

And now - regarding your code.

You have found hello world code for Oberon system, which is more complicated.
With voc, it's much easier like this

MODULE Hello;

IMPORT Console;

BEGIN

Console.String("hello"); Console.Ln

END Hello.

I'll write more comments regarding your code a little bit later. It's also possible to write a Hello world in Oberon system way., but a little bit differently.

**Comment by norayr** [comment]
Hey, Srinias.

With today's update, this code

<code>
MODULE Hello;
 IMPORT Oberon, Texts;
   VAR W: Texts.Writer;
 PROCEDURE World*;
   BEGIN
     Texts.WriteString(W, "Hello World!");
     Texts.WriteLn(W);
     Texts.Append(Oberon.Log, W.buf);
     Oberon.DumpLog;
  END World;

 BEGIN
   Texts.OpenWriter(W);
   World
 END Hello.
</code>

works fine.

The only difference with Oberon system version is that in Oberon system you can call from the shell Hello.World function, while in Linux there is only one entrance point, and in the main module it's a section which starts with BEGIN keyword.

Thus you need to call World procedure from that part.

**Comment by snayaksnayak** [comment]
Agree.
Linux has one entry point starting at BEGIN. So one has to call World inside BEGIN. Fine.
Yes, Oberon.DumpLog inside World procedure is good. One can even dump Log to windows command prompt.
