### ISSUE TITLE
Which modules are available by default in voc?

### ISSUE THREAD

**Issue by snayaksnayak** [norayr/voc#23]
Like Oberon module, Texts module, which all modules are available in voc by default?
Does this module list covers all default/necessary modules supported by Oberon system?

**Comment by norayr** [comment]
very good question.

On my system, voc is prefixed in /opt/.

Therefore, I can know which libraries are available by doing

```
 ls /opt/voc/lib/voc/sym/
```

Then, you can know interface of each module by running

```
/opt/voc/bin/showdef /opt/voc/lib/voc/sym/Strings.sym
```

**Comment by norayr** [comment]
no, not all the modules from the Oberon system have been ported.

porting modules that do not necessarily depend on graphics is easier. porting modules that do depend of graphics, is harder.

but many other modules from other compiler libraries have been ported.

**Comment by snayaksnayak** [comment]
True. Modules depending on Graphics are harder.
Even though I raised the question, I too don't know which modules are default/necessary that is supported by Oberon system. Any hint?

**Comment by norayr** [comment]
There is no standard actually. Even ETH Oberon had different versions, with different versions of OP2, and different sets of modules. And there is a Ulm Oberon System which had completely different and incompatible set of modules.

One effort to create a standard was designing [Oakwood Guidelines](http://wiki.oberon.vishap.am/index.php/Oakwood_Guidelines). I believe, all those modules are available in voc. May be only Out.Mod is not fully implemented now. Module Console has almost identical interface, so I usually import it with aliasing ```IMPORT Out := Console;```

Bringing different libraries from different projects to be available for voc users was one of the main goals of the project.

**Comment by snayaksnayak** [comment]
That's nice.
