### ISSUE TITLE
Difference between programming on Oberon system and voc in Linux w.r.t. garbage collector.

### ISSUE THREAD

**Issue by snayaksnayak** [norayr/voc#25]
I think, while using voc to program, one can't take advantage of garbage collector.
Am I mistaken?

**Comment by norayr** [comment]
libVishapOberon provides a garbage collector. It's sources are in SYSTEM.Mod. Memory get's free automatically.

There are ways to bypass the garbage collector. For example, define P = POINTER [1] TO PDesc; This won't be counted by GC.

If necessary, it's possible to implemente your own Dispose() or Free() function, and use manual memory management. By default memory is managed by mark and sweep garbage collector.

**Comment by snayaksnayak** [comment]
That's good news, at least for me...
I was mistaken.
