### ISSUE TITLE
How far voc supports Oberon 7?

### ISSUE THREAD

**Issue by snayaksnayak** [norayr/voc#26]
Voc is a Oberon-2 compiler.
Oberon-2 is a super set of Oberon.
Oberon-7 used in Project Oberon 2013 is simpler than Oberon.
How far voc supports Oberon 7? Any part of Oberon-7 is yet to implement?

**Comment by norayr** [comment]
voc is an Oberon-2 compiler.

currently, in the voc's source [tree](https://github.com/norayr/voc/tree/master/src/voc07R), there is an Oberon-7 compiler. It's just a port of the Project Oberon 2013's oberon-07 compiler, which can be run on Linux. It generates .rsc files that can be run on Oberon RISC hardware, or in Peter De Wachter's [emulator](https://github.com/pdewacht/oberon-risc-emu).

As I've implemented a x86 backend for a very old version of that compiler, may be I'll try to connect it to this version one day, and also make a x86_64 version.

**Comment by snayaksnayak** [comment]
Wow. This is great news. You have x86 backend for old Oberon compiler. If it gets connected to Oberon 7, then one can simply program in Oberon 7 and get his program running on x86.

But is it that, Oberon 7 will stay for sometime...or Oberon 7 will evolve to Oberon 16 or Oberon 17...

**Comment by norayr** [comment]
I believe that today Oberon-2 is a most practical language for real life use. That's arguable, of course.

**Comment by snayaksnayak** [comment]
Oh, that's why I see many compilers available for Oberon-2 but hardly any for Oberon-7.

**Comment by norayr** [comment]
May be because it has long history, which implies legacy compilers, while the new language is just emerging, and still changes.
