### ISSUE TITLE
Which Oberon?

### ISSUE THREAD

**Issue by jkleiser** [norayr/voc#3]
I think the README.md should tell whether voc is Oberon-2 or Oberon-07, and it would also be nice with a link to some basic Oberon reference documentation.

**Comment by jkleiser** [comment]
Sorry, I forgot to go back and check this page http://oberon.vishap.am. It says clearly: "ⱱishap Oberon Compiler (voc) is a free (GPLv3) professional oberon-2 compiler."
But I guess it should have been "Vishap Oberon Compiler (voc) . . ." with a "V" first.

**Comment by norayr** [comment]
added link to the home page to the github repository information.
