### ISSUE TITLE
Errors in voc/COMPILE re. Mac OSX

### ISSUE THREAD

**Issue by jkleiser** [norayr/voc#6]
On my Mac, with OSX 10.11.2, I got
```
-bash: gmake: command not found
```
so I just used make instead.
And the name of the makefile is "makefile.darwin.clang.x86_64", not "makefile.clang.darwin.x86_64" as your COMPILE says two places.

**Comment by norayr** [comment]
did plain osx make work? hmm, i'll test it. i remember that there's used some syntax in the makefiles that needs gmake. i'll test it.

makefile name fixed in the "COMPILE" file for darwin.

Thank you.

**Comment by jkleiser** [comment]
Yes, plain OSX make worked well for me.
